spring:
  datasource:
    username: ${DB_BT_USERNAME}
    password: ${DB_BT_PASSWORD}
    url: ${DB_BT_URL}
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
    enabled: false

server:
  port: ${MS_BT_PORT}

springdoc:
  swagger-ui:
    path: /swagger-ui-buesiness-trip.html

client:
  minio:
    int:
      url: ${CLIENT_MS_MINIO_URL}

  users:
    int:
      url: ${CLINET_MS_USER_URL}

  permission:
    int:
      url: ${CLIENT_MS_PERMISSION_URL}

management:
  endpoint:
    health:
      enabled: true
